sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
  - cp .travis-toolchain.xml ~/.m2/toolchains.xml
install: 
  - mvn verify -B
addons:
  apt:
    packages: 
      - openjdk-6-jdk