sudo: true
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
  - sudo ls
  - cp /.travis-toolchain.xml ~/.m2/toolchains.xml
addons:
  apt:
    packages: 
      - openjdk-6-jdk